uploads = []
generated = []

[[outputs]]
id = "USvq8UApasnjkW04nNqCV"
uri = "file://school-map-site.tar.gz"
type = "unspecified"
title = "액상형 전자담배 매장 지도 - 빌드 파일"

[[outputs]]
id = "pFfiwf9xRkDAy7Z1VwMGG"
uri = "file://담배매장_업로드_템플릿.csv"
type = "table"
title = "담배 매장 업로드 템플릿"

[[outputs]]
id = "Xdys5HYy3LEhe8fARQCKA"
uri = "file://학교_업로드_템플릿.csv"
type = "table"
title = "학교 업로드 템플릿"
