// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tobacco-markers/StyleA.tsx": () => import("../components/mockups/tobacco-markers/StyleA.tsx"),
  "./components/mockups/tobacco-markers/StyleB.tsx": () => import("../components/mockups/tobacco-markers/StyleB.tsx"),
  "./components/mockups/tobacco-markers/StyleC.tsx": () => import("../components/mockups/tobacco-markers/StyleC.tsx"),
  "./components/mockups/tobacco-markers/StyleD.tsx": () => import("../components/mockups/tobacco-markers/StyleD.tsx"),
  "./components/mockups/tobacco-markers/StyleE.tsx": () => import("../components/mockups/tobacco-markers/StyleE.tsx"),
  "./components/mockups/tobacco-markers/StyleF.tsx": () => import("../components/mockups/tobacco-markers/StyleF.tsx"),
  "./components/mockups/tobacco-markers/VapeIcon.tsx": () => import("../components/mockups/tobacco-markers/VapeIcon.tsx"),
  "./components/mockups/tobacco-icons/TobaccoIcons.tsx": () => import("../components/mockups/tobacco-icons/TobaccoIcons.tsx")
};
