// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tobacco-icons/TobaccoIcons.tsx": () => import("../components/mockups/tobacco-icons/TobaccoIcons.tsx")
};
